name: Civility - The Origin of Bed Beard
favicon: null
layout_spectrum: 0.27271597692742944
typography_spectrum: 0.965300285955891
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.18620135728269815
  lightness: 0.2305976036004722
  saturation: 0.6037148432806134
  rhythmicContrast: 0.026662865420803428
purpose: []
